# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache site content
        id: content
        uses: actions/cache@v2
        with:
          path: packages/stack/sveltekit
          key: ${{ runner.os }}-content
      - name: Cache pnpm modules
        id: pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.0
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: pnpm
      - run: pnpm install
      - run: pnpm build

  deploy-demo:
    name: Deploy demo site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache site content
        id: content
        uses: actions/cache@v2
        with:
          path: packages/stack/sveltekit
          key: ${{ runner.os }}-content
      - name: Cache pnpm modules
        id: pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.0
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: pnpm
      - run: pnpm install
      - run: pnpm deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
  
  deploy-test:
    name: Deploy test site
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache site content
        id: content
        uses: actions/cache@v2
        with:
          path: packages/stack/sveltekit
          key: ${{ runner.os }}-content
      - name: Cache pnpm modules
        id: pnpm
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v2.2.0
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: pnpm
      - run: pnpm install
      - run: pnpm deploy-test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
