# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches: [main]

jobs:
  builds-on-every-os:
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [16.x, 18.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.19
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          # cache: pnpm
      - run: node --version
      - run: pnpm --version
      - run: pnpm adapter-deps
      - run: pnpm build-adapter
      - run: pnpm install
      - run: pnpm build-sample

  deploy-demo:
    name: Deploy demo site
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          # cache: pnpm
      - run: pnpm adapter-deps
      - run: pnpm build-adapter
      - run: pnpm install
      - run: pnpm build-sample
      - run: pnpm deploy-sample
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-central-1"
  
  # deploy-test:
  #   name: Deploy test site
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: pnpm/action-setup@v2.2.0
  #       with:
  #         version: latest
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: "16.x"
  #         cache: pnpm
  #     - run: pnpm adapter-deps
  #     - run: pnpm build-adapter
  #     - run: pnpm install
  #     - run: pnpm build-test
  #     - run: pnpm deploy-test
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         AWS_DEFAULT_REGION: "eu-central-1"
